=== Orpsemius/orpsemius.github.io/branches.dtd
<!ELEMENT branches (branch+)>
<!ELEMENT branch (address, contact, openingHours, link)>
<!ELEMENT address (#PCDATA)>
<!ELEMENT contact (#PCDATA)>
<!ELEMENT openingHours (#PCDATA)>
<!ELEMENT link (#PCDATA)>

=== Orpsemius/orpsemius.github.io/branches.xml
<?xml version="1.0"?>
<!DOCTYPE branches SYSTEM "branches.dtd">

<branches>
    <branch>
        <address>76 Devonshire St, Surry Hills NSW</address>
        <contact>02 9211 1234</contact>
        <openingHours>Mon-Fri: 6:00 to 14:30. Sat-Sun: 7:00 to 15:00</openingHours>
        <link>https://maps.app.goo.gl/Z7nhkpHwLownzLzr6</link>
    </branch>
    <branch>
        <address>451 Pitt St, Haymarket Sydney, NSW</address>
        <contact>02 9262 5678</contact>
        <openingHours>Mon-Fri: 6:00 to 16:00, Sat-Sun: 7:00 to 15:00</openingHours>
        <link>https://maps.app.goo.gl/jcNejKLRvvaAueUv5</link>
    </branch>
    <branch>
        <address>31 Alfred Street, Circular Quay, NSW</address>
        <contact>02 8971 9101</contact>
        <openingHours>Mon-Fri: 6:00 to 16:00, Sat-Sun: 7:00 to 15:00</openingHours>
        <link>https://maps.app.goo.gl/Bp2HPjTA9gCQgPDr9</link>
    </branch>
</branches>
