=== Orpsemius/orpsemius.github.io/menu.dtd
<!ELEMENT menu (meals, beverages)>
    <!ELEMENT meals (meal+)>
    <!ELEMENT meal (name, price, description, image)>
    <!ELEMENT beverages (coffeeAndChocolate, otherBeverage+)>
    <!ELEMENT coffeeAndChocolate (variation+, descriptionCoffeeAndChocolate)>
    <!ELEMENT variation (size, price, image)>
    <!ELEMENT otherBeverage (name,price, image)>
    <!ELEMENT name (#PCDATA)>
    <!ELEMENT price (#PCDATA)>
    <!ELEMENT description (#PCDATA)>
    <!ELEMENT size (#PCDATA)>
    <!ELEMENT image (#PCDATA)>
    <!ELEMENT descriptionCoffeeAndChocolate (#PCDATA)>

=== Orpsemius/orpsemius.github.io/menu.xml
<?xml version="1.0"?>
<!DOCTYPE menu SYSTEM "menu.dtd">
<menu>
    <meals>
        <meal>
            <name>Beetroot and feta salad</name>
            <price>$15.00</price>
            <description>Suitable for vegetarians, made with fresh beetroot</description>
            <image>beetrootFetaSalad.jpeg</image>
        </meal>
        <meal>
            <name>Sourdough Rye Sandwich</name>
            <price>$18.00</price>
            <description>Cheese and salad sandwich made with organic, sourdough rye bread</description>
            <image>sourdoughRyeSandwich.jpeg</image>
        </meal>
        <meal>
            <name>Spinach Pie and Salad</name>
            <price>$20.00 </price>
            <description>Tasty pie with salad</description>
            <image>spinachPieSalad.jpeg</image>
        </meal>
        <meal>
            <name>Feta pancakes with salad</name>
            <price>$19.50 </price>
            <description>Tasty pancake filled with feta and salad</description>
            <image>fetaPancakeSalad.jpeg</image>
        </meal>

    </meals>
    
    <beverages>
        <coffeeAndChocolate>
            <variation>
                <size>Small</size>
                <price>$3.50 </price>
                <image>smalCC.jpeg</image>
            </variation>
            <variation>
                <size>Regular</size>
                <price>$4.00</price>
                <image>regularCC.jpeg</image>
            </variation>
            <variation>
                <size>Large</size>
                <price>$4.50</price>
                <image>bigCC.jpeg</image>
            </variation>
            <descriptionCoffeeAndChocolate>For coffee, please inform the staff of the coffee type</descriptionCoffeeAndChocolate>
        </coffeeAndChocolate>

        <otherBeverage>
            <name>Soda</name>
            <price>$3.00</price>
            <image>soda.jpeg</image>
        </otherBeverage>
        <otherBeverage>
            <name>Fresh Juice</name>
            <price>$6.00</price>
            <image>juice.jpeg</image>
        </otherBeverage>
        <otherBeverage>
            <name>Bottled Water</name>
            <price>$2.00</price>
            <image>water.jpeg</image>
        </otherBeverage>


    </beverages>
</menu>
